In [2]:
import numpy as np


A = np.array([[1,2],[2,3]]) @ np.array([[1],[2]])
B = 2 * np.array([[1,2,3],[4,5,6]])
C = 1 + A
D = B @ C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [3]:
A

array([[5],
       [8]])

In [4]:

B

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
C

array([[6],
       [9]])